---
name: Egg-Plugin-Cache-UA
version: 0.01
author:
  - 'Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>'
abstract: The result of LWP is cached for Egg::Plugin.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Egg::Plugin::Cache: 2.01
  Egg::Plugin::LWP: 2.01
  Egg::Release: 2
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Egg::Plugin::Cache::UA:
    file: lib/Egg/Plugin/Cache/UA.pm
    version: 0.01
  Egg::Plugin::Cache::UA::handler:
    file: lib/Egg/Plugin/Cache/UA.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
